services:
  postgre_go:
    image: postgres:15.4
    container_name: tablelink-test
    hostname: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_tablelink_volumes:/var/lib/postgresql/data
    networks:
      - pg_tablelink_network

networks:
  pg_tablelink_network: {}

volumes:
  pg_tablelink_volumes: {}
